apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend
  name: backend
spec:
  replicas: 2
  strategy: 
    type: Recreate
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - image: osamagharib/pip-backend
        name: backend
        env:
        - name: ROOT_PATH
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: BACKEND_ROOT_PATH
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: BACKEND_PORT

        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DB_HOST          
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DB_PORT
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DB_NAME
                    
        - name: RABBIT_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: RABBIT_HOST
        - name: RABBIT_PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: RABBIT_PORT
            
        - name: JWT_KEY
          valueFrom:
            secretKeyRef:
              name: jwt
              key: key
        
        resources: {}
        ports:
        - containerPort: 3000
        volumeMounts:
          - name: backend-images
            mountPath: /app/images
      volumes:
        - name: backend-images
          hostPath:
            path: /tmp/backend-images
            type: DirectoryOrCreate
